/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      spacing: {
        "unit": "4px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "max-width": "1440px",
        "margin-mobile": "20px"
      },
      colors: {
        "primary": "#c3f5ff",
        "secondary": "#ecb2ff",
        "surface": "#131315",
        "inverse-primary": "#006875",
        "on-error": "#690005",
        "surface-bright": "#39393b",
        "surface-variant": "#353437",
        "on-primary": "#00363d",
        "inverse-on-surface": "#313032",
        "on-primary-fixed": "#001f24",
        "on-secondary-container": "#480063",
        "tertiary": "#a8ffd2",
        "surface-dim": "#131315",
        "on-secondary-fixed": "#320047",
        "primary-fixed": "#9cf0ff",
        "on-tertiary-container": "#006645",
        "surface-tint": "#00daf3",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#002113",
        "secondary-fixed": "#f8d8ff",
        "surface-container-highest": "#353437",
        "inverse-surface": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "on-tertiary": "#003824",
        "on-primary-fixed-variant": "#004f58",
        "primary-container": "#00e5ff",
        "error-container": "#93000a",
        "on-secondary": "#520071",
        "on-surface": "#e5e1e4",
        "on-background": "#e5e1e4",
        "surface-container": "#201f22",
        "on-surface-variant": "#bac9cc",
        "on-secondary-fixed-variant": "#74009f",
        "outline": "#849396",
        "secondary-fixed-dim": "#ecb2ff",
        "tertiary-container": "#5be9ad",
        "background": "#131315",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#3b494c",
        "primary-fixed-dim": "#00daf3",
        "surface-container-lowest": "#0e0e10",
        "error": "#ffb4ab",
        "secondary-container": "#cf5cff",
        "surface-container-low": "#1c1b1d",
        "on-primary-container": "#00626e",
        // standard tailwind variables mapped for shadcn
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "mono-data": ["Space Grotesk"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
